### ISSUE TITLE
Could not parse request object: Expected object for field libraries, found STRING

### ISSUE THREAD

**Issue by koder101** [gbrueckl/Databricks.API.PowerShell#10]
Hi, 

I am getting the below error for **-Libraries** parameter in **Add-DatabricksJob** command. The below syntax is not working -

`$libraries = @{"jar" = "dbfs:/jars/sqldb.jar"}`

**Error:**

> Invoke-RestMethod : {"error_code":"MALFORMED_REQUEST","message":"Could not parse request object: Expected object for field libraries, found STRING"}

**Verbose output:**

```
"libraries":  [
                      "System.Collections.Hashtable"
                  ],
```
Could you please look into this.

**Comment by koder101** [comment]
@gbrueckl :

Interestingly when I am testing the exact same functions manually, then the body is getting converted to json as expected. _Absolutely no idea why it's happening._

**Code snippet tested:**

```
Function Add-Property
{	
         # blah blah
}
Function Add-PropertyIfNotExists
{	
         # blah blah
}

$parameters = @{}
$name = "James"
$type = "WestEurope"

$schedule = @{
			"quartz_cron_expression" = "0 45 * * * ?"
			"timezone_id" = "US/Pacific"
			}

$libraries = @(@{
    "jar" = "dbfs:/jars/sqldb.jar"
    })

$parameters | Add-Property -Name "name" -Value $name
$parameters | Add-Property -Name "type" -Value $type
$parameters | Add-Property -Name "libraries" -Value $libraries
$parameters | Add-Property -Name "schedule" -Value $schedule

$Body = $parameters | ConvertTo-Json -Depth 20

$Body
Write-Host "Body: `n$($Body)"
```

**Output:**

```

{
    "libraries":  [
                      {
                          "jar":  "dbfs:/jars/sqldb.jar"
                      }
                  ],
    "name":  "James",
    "type":  "WestEurope",
    "schedule":  {
                     "timezone_id":  "US/Pacific",
                     "quartz_cron_expression":  "0 45 * * * ?"
                 }
}
Body: 
{
    "libraries":  [
                      {
                          "jar":  "dbfs:/jars/sqldb.jar"
                      }
                  ],
    "name":  "James",
    "type":  "WestEurope",
    "schedule":  {
                     "timezone_id":  "US/Pacific",
                     "quartz_cron_expression":  "0 45 * * * ?"
                 }
}
```

**Comment by gbrueckl** [comment]
did you try 9.2.0 yet (just published like 30 mins ago?
also, the JSON-Body looks fine to me in your last example and looks similar to what 9.2.0 is creating

**Comment by koder101** [comment]
@gbrueckl :
Sure let me try, I actually installed the module through PSGallerry, looks like 9.20. isn't published to PSGallery.

**Comment by koder101** [comment]
@gbrueckl :
Sorry, I was refreshing the same older link (9.1.0), just got it - https://www.powershellgallery.com/packages/DatabricksPS/0.9.2.0

**Comment by koder101** [comment]
@gbrueckl 
Thanks!!! It worked 👍 
You can close this issue.

**Comment by gbrueckl** [comment]
great, and thanks again for providing feedback!

**Comment by gbrueckl** [comment]
and btw, if you have any  blocking issues where the module/API is not working as expected, you can always use
`Invoke-DatabricksApiRequest -Method $requestMethod -EndPoint $apiEndpoint -Body $parameters`
until I fix the issue :)
