### ISSUE TITLE
Import-Export doesn't works

### ISSUE THREAD

**Issue by pcocko** [gbrueckl/Databricks.API.PowerShell#17]
It is giving error on "Import-DatabricksEnvironment" procedure because 

`Import-DatabricksEnvironment -LocalPath $workspaceItem.FullName -Artifacts Workspace -WorkspaceOverwriteExistingItems:$OverwriteExistingWorkspaceItems -ClusterUpdateExisting:$UpdateExistingClusters -JobUpdateExisting:$UpdateExistingJobs`

should be

`Import-DatabricksEnvironment -LocalPath $workspaceItem.FullName -Artifacts Workspace -OverwriteExistingWorkspaceItems:$OverwriteExistingWorkspaceItems -UpdateExistingClusters:$UpdateExistingClusters -UpdateExistingJobs:$UpdateExistingJobs`

**Comment by gbrueckl** [comment]
thanks for the hint!
just fixed it and published 0.9.3.8 to the gallery
