### ISSUE TITLE
Start-DatabricksJob Validation fails

### ISSUE THREAD

**Issue by abbgrade** [gbrueckl/Databricks.API.PowerShell#18]
Hello,

if you run `Add-DatabricksJob` and then `Start-DatabricksJob`, the JobID parameter validation fails, since the new job id is not part of the validation set. It works, if you wait a few seconds between the steps.

Best regards,
Steffen

**Comment by gbrueckl** [comment]
Hi Steffen,

when running Set-DatabricksEnvironment there is an optional 3rd parameter called -DynamicParameterCacheTimeout which allows you to set the time a cached value - e.g. for JobIDs - is valid. The idea behind this is to improve overall performance and usability of the cmdlets. You can of course lower this value (default is 5 seconds) and see if it helps solving your problem 

you can also simply start a notebook/JAR/... without creating a job beforehand by using New-DatabricksJobRun without specifying a JobID

regards,
-gerhard

**Comment by gbrueckl** [comment]
as I did not hear any further complaints and explained the reason why the module behaves like this I will close this issue
