### ISSUE TITLE
Calling "Add-DatabricksSCIMUser" throws "Parameter set cannot be resolved using the specified named parameters."

### ISSUE THREAD

**Issue by DoUCodeBro** [gbrueckl/Databricks.API.PowerShell#19]
Based my calls on the function documentation and example. (i.e "Add-DatabricksSCIMUser -UserName John.doe@test.com -Groups admins -Entitlements allow-cluster-create -Verbose")

This cmdlet works in v 0.9.5.2

**Comment by gbrueckl** [comment]
This was changed some time ago when also the dynamic parameters (for IntelliSense/AutoComplete) were removed for performance reasons.
the new call should look like this:
`Add-DatabricksSCIMUser -UserName John.doe@test.com -GroupNames admins -Entitlements allow-cluster-create -Verbose`
(change `-Groups` to `-GroupNames` or `-GroupIDs`)

I also just updated the inline documentation which will then be public with the next release!
