### ISSUE TITLE
Set-DatabricksEnvironment with Service Principal 

### ISSUE THREAD

**Issue by EdiFirst** [gbrueckl/Databricks.API.PowerShell#20]
Hey @gbrueckl congratulations and thank you by doing an excelent content to community. 
I'm fancing the follow error when  run the command _Set-DatabricksEnvironment_ after try authenticate on databricks service using service principal:

_**Set-DatabricksEnvironment : Parameter -ApiRootUrl or -CustomApiRootUrl needs to be specified!**_

Ok I passed the parameter point out  to https://{region}.azuredatabricks.net

Then I received the following error after ran _Export-DatabricksEnvironment -LocalPath $LocalPath `
 -Artifacts "Workspace" -WorkspaceRootPath "/"_ :

`Invoke-RestMethod : 
Error 403 User not authorized.
HTTP ERROR 403
Problem accessing /api/2.0/workspace/list. Reason:
    User not authorized.
No C:\Users{mypath}\1.0.4.0\Public\General.ps1:85 
caractere:13

+ ...   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-R 
   estMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRest 
   MethodCommand`

But I created the service principal and gave permission api to Databricks as described on documentation. Could you please suggest something?

**Comment by gbrueckl** [comment]
please check out my blog post where I explained AAD authentication in more details and it also includes examples
https://blog.gbrueckl.at/2020/06/databricksps-and-azure-ad-authentication/

if you get 403 User not authorized then you very likely have some issues with your permissions
you can use -Verbose flag to track down the issue which will expose the whole REST API call including all parameters

**Comment by EdiFirst** [comment]
On really I come from this documentation, I tried the same command with -Verbose option, I can see the token was generated but I have no ideia why I still getting the same error, on the application (service principal) I gave autorization to my user as described:
https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/assign-user-or-group-access-portal

I'll try get the token to service principal with the **Cliente-Credentials-flows** approach perhaps thats works. 

I just installed your extension to VsCode as well , with my PAT its bring the objects, but my challenge here is build a CI/CD with Azure DevOps more smooth  possible, withless manual steps and expose secrets on the code or files.

**Comment by gbrueckl** [comment]
Please check this document which is specific to AAD and Databricks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by EdiFirst** [comment]
> Please check this document which is specific to AAD and Databricks Get Outlook for Android<https://aka.ms/ghei36>

This page is jump in outlook  mobile product.

**Comment by gbrueckl** [comment]
https://github.com/gbrueckl/Databricks.API.PowerShell/blob/master/Docs/Authentication%20using%20AAD%20service%20principal.pdf

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by EdiFirst** [comment]
Ok , Im really getting alot troubles and "walking" slowly..I finally get token, the issues was because of the resource, I was passing: https://management.core.windows.net/ when should be the id of databricks,  but to consume the service is necessary to use the management access token (which is different of the Bearer Token) or Token just one parameter: org.id. But still receiving the 403:

`<body>
	<h2>HTTP ERROR 403</h2>
	<p>Problem accessing /api/2.0/clusters/list. Reason:
		<pre>    User not authorized.</pre>
	</p>
</body>`

So I'll try again with another service principal, I'll re create one from zero. I'm not sure what is wrong with that. Thank you very much by all your help!

**Comment by gbrueckl** [comment]
if you set up your service principal as described in the PDF above and use the code from the blog post it should work. Right now it seems that you may have set up the service principal correctly but did not grant it permissions on the Azure Databricks resource in the Azure Portal using Access Control (IAM)

**Comment by EdiFirst** [comment]
> if you set up your service principal as described in the PDF above and use the code from the blog post it should work. Right now it seems that you may have set up the service principal correctly but did not grant it permissions on the Azure Databricks resource in the Azure Portal using Access Control (IAM)

Thank you @gbrueckl , yep this was it! But had another stuff as well, the ResourceId which in the api is the header **X-Databricks-Azure-Workspace-Resource-Id** , I was typing the workspace name, but I realize that it was "waiting for" the name of databricks node/instance, after change that finally works! 

About CI/CD How Can'I work in an seamlessly away ? Seems it not fully documented on _DatabricksPS_ , I'm not sure how I can get the best of these two tools. I know that in your VsCode extension is best to bring me all objects, I believe it it allow me debugger or run notebooks , edit python functions locally and upload this to cloud Databricks but is necessary to use PAT  on the config file , that I would like to avoid. I can use _DatabricksPS_  to avoid that , but I'm not sure how continue on this process , to edit python function, .whl libraries and specially run Dbutils ( to that I know I need Databricks Connect) but this one use PAT too, sorry the confusion, but I'm not developer my challenge here is delivery the CI/CD. Can you please give me an ideia?

**Comment by gbrueckl** [comment]
so there are various points here:
First of all you need to get your notebooks into GIT by either:
 1) manually linking each notebook directly in the Databricks UI (not recommended as it is very fragile and notebook-by-notebook)
 2) use the VSCode extension to download the notebooks
 3) use DatabricksPS and run Export-DatabricksEnvironment cmdlet 
Option directly puts the notebooks into GIT whereas 2) and 3) allow you to manually commit whatever changes you want to commit - it is just working with any other files and GIT

once they are in GIT, you can create a CI/CD pipeline. As these are only notebooks/.py/.r/.scala files, it is usually not necessary to build them but you can simply copy them to your artifacts store which is then used for your releases

To deploy the notebooks again as part of the CI/CD release pipeline, you can use DatabricksPS Import-DatabricksEnvironment

depending on your CI/CD tool, you can specify secret values for your PAT/service principal/username/password

**Comment by EdiFirst** [comment]
> so there are various points here:
> First of all you need to get your notebooks into GIT by either:
> 
> 1. manually linking each notebook directly in the Databricks UI (not recommended as it is very fragile and notebook-by-notebook)
> 2. use the VSCode extension to download the notebooks
> 3. use DatabricksPS and run Export-DatabricksEnvironment cmdlet
>    Option directly puts the notebooks into GIT whereas 2) and 3) allow you to manually commit whatever changes you want to commit - it is just working with any other files and GIT
> 
> once they are in GIT, you can create a CI/CD pipeline. As these are only notebooks/.py/.r/.scala files, it is usually not necessary to build them but you can simply copy them to your artifacts store which is then used for your releases
> 
> To deploy the notebooks again as part of the CI/CD release pipeline, you can use DatabricksPS Import-DatabricksEnvironment
> 
> depending on your CI/CD tool, you can specify secret values for your PAT/service principal/username/password

Ok , thank you very much @gbrueckl I'll build the 3rd approach + Azure DevOps CI/CD.
