### ISSUE TITLE
Receiving Strange Error When Using the Add-DatabricksCluster cmdlet

### ISSUE THREAD

**Issue by briancuster** [gbrueckl/Databricks.API.PowerShell#21]
I'm receiving a strange error when using the Add-DatabricksCluster cmdlet.  The error message states:  {"error_code":"INVALID_PARAMETER_VALUE","message":"Missing required field: size"}.  I have no idea what this is referring to and it is preventing me from creating a cluster in my workspace.  Do you guys know what this means and what I should do about it?  I am passing in the following arguments:  SparkVersion = 7.0.x-scala 2.12, nodetypeid = "Standard_DS3_v2", NumWorkers = 1, ClusterName = "myCluster", SparkEnvVars = HashTable, ClusterMode="HighConcurrency", Autoterminationinminutes = 60, and PythonVersion = "3 (3.5)".  Please advise what I am doing wrong.

**Comment by gbrueckl** [comment]
Can you please use the -Verbose switch and check what's sent to the REST API in the background?
Please further check if it is correct according to the API specifications

You may also try passing in a Cluster Definition object via the parameter with the same name

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by briancuster** [comment]
What should I put in the cluster definition object?  I'm not sure how to use this parameter.

**Comment by gbrueckl** [comment]
You can navigate to your cluster in the Databricks GUI and viw the JSON. Then use Convert From-Json cmdlet to convert it to a PS Object which you can use as -ClusterDefinition parameter then

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by briancuster** [comment]
ARe you referring to the ClusterObject parameter?  I don't see a ClusterDefinition parameter?

**Comment by briancuster** [comment]
With the verbose parameter i am still seeing the following error message:  {"error_code":"INVALID_PARAMETER_VALUE","message":"Missing required field: size"}

**Comment by gbrueckl** [comment]
Yes, ClusterObject parameter (sorry, I am not in front of my PC at the moment)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gbrueckl** [comment]
Sure, but you see the exact api request that is sent in your output window, no?
Then you can debug from there

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by briancuster** [comment]
I was finally able to create a cluster!  I think I was passing in the wrong SparkVersion parameter value and that was throwing it off.  After copying the correct version from an existing cluster I was able to create one with no problem.  I guess I will have to provide my users a lookup for both ClusterVersion and nodeTypeId since there are so many values.  Any thoughts on this?

**Comment by gbrueckl** [comment]
Actually it should only allow valid values as these are dynamic parameters
They are sourced by Get-DatabricksNodeType and Get-DatabricksSparkVersion
You can also use those Cmdlets to get the list of available values and let the users choose themselves

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gbrueckl** [comment]
due to inactivity and no further comments this issue will be closed
