### ISSUE TITLE
Get-DatabricksCluster Returns Null

### ISSUE THREAD

**Issue by briancuster** [gbrueckl/Databricks.API.PowerShell#22]
I'm calling the Get-DatabricksCluster cmdlet and it is returning null even though as I debug, when it goes into your method, the return value is an array of clusters but by the time it gets back to my function it just returns null.  What am I doing wrong with this cmdlet?  Thanks.

**Comment by gbrueckl** [comment]
`Get-DatabricksCluster` without any parameter returns an array of clusters that you have access too
if this array is empty, you either do not have any clusters defined or do not have access 
please note that the parameter `-ClusterID` is not mandatory. If you skip it, all clusters will be returned!
If you specify a `-ClusterID`, a single PSObject is returned instead of an array of

**Comment by briancuster** [comment]
And that is the weird thing.  As I said, when I use the cmdlet without any parameters, I see the results as they return from your code but by the time it reaches my code, the result is null!  Now, I am no longer able to call the cmdlet at all because during debugging, I step right over the calling code and nothing happens.  It's the strangest thing.  Is your code compatible with PowerShell 7.0?

**Comment by gbrueckl** [comment]
yes, it should also work with PS 7.0

can you run the cmdlet using `-Verbose` ?
this will also display the native PS Invoke-RestMethod call which you can also execute manually then

**PS 7.0:**
```
$PSVersionTable
$x = Get-DatabricksCluster
$x.GetType()
$x[0] | ConvertTo-Json
```
```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array

{
  "cluster_id": "0522-075955-corns241",
  "spark_context_id": 7617047476099549573,
  "cluster_name": "EventHub",
  "spark_version": "6.5.x-scala2.11",
  "spark_conf": {
    "spark.databricks.io.cache.enabled": "true",
    "spark.databricks.service.server.enabled": "true",
    "spark.databricks.delta.optimizeWrite.enabled": "True",
    "spark.databricks.pyspark.enableProcessIsolation": "False",
    "spark.databricks.delta.autoCompact.enabled": "True",
    "spark.databricks.delta.optimize.maxFileSize": "134017728",
    "spark.databricks.delta.preview.enabled": "true",
    "spark.sql.thriftServer.incrementalCollect": "False",
    "spark.sql.statistics.histogram.enabled": "False"
  },
  "node_type_id": "Standard_F4s",
  "driver_node_type_id": "Standard_F4s",
  "spark_env_vars": {
    "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
  },
  "autotermination_minutes": 240,
  "enable_elastic_disk": true,
  "cluster_source": "UI",
  "enable_local_disk_encryption": false,
  "azure_attributes": {
    "first_on_demand": 0,
    "availability": "ON_DEMAND_AZURE",
    "spot_bid_max_price": -1.0
  },
  "state": "TERMINATED",
  "state_message": "Inactive cluster terminated (inactive for 240 minutes).",
  "start_time": 1590134396064,
  "terminated_time": 1592911798188,
  "last_state_loss_time": 1592818742445,
  "num_workers": 1,
  "default_tags": {
    "Vendor": "Databricks",
    "Creator": "gerhard@gbrueckl.at",
    "ClusterName": "EventHub",
    "ClusterId": "0522-075955-corns241"
  },
  "creator_user_name": "gerhard@gbrueckl.at",
  "termination_reason": {
    "code": "INACTIVITY",
    "parameters": {
      "inactivity_duration_min": "240"
    },
    "type": "SUCCESS"
  },
  "pinned_by_user_name": "8745330677002057",
  "init_scripts_safe_mode": false
}
```

**Comment by briancuster** [comment]
I tried running it with -Verbose and again the debugger just steps into the line without calling your function.  I get nothing back from the call.

**Comment by briancuster** [comment]
Okay, looks like after I checked in my commits it is again calling your function and I'm getting results this time which is great.  So I think everything is okay again.  Sorry to have bothered you on this.

**Comment by gbrueckl** [comment]
ok, good to hear :) 
will close this issue then
