### ISSUE TITLE
New workspace urls not supported

### ISSUE THREAD

**Issue by hurtn** [gbrueckl/Databricks.API.PowerShell#23]
Hello, not sure if user error but doesn't seem like new url formats are supported. 
Set-DatabricksEnvironment : Cannot validate argument on parameter 'ApiRootUrl'. The argument "https://adb-xxxxxx0.0.azuredatabricks.net" does 
not belong to the set "https://australiacentral.azuredatabricks.net,https://australiacentral2.azuredatabricks.net,https://australiaeast.azuredatabricks.ne
t,https://australiasoutheast.azuredatabricks.net,https://brazilsouth.azuredatabricks.net,https://canadacentral.azuredatabricks.net,https://canadaeast.azur 
edatabricks.net,https://centralindia.azuredatabricks.net,https://centralus.azuredatabricks.net,https://eastasia.azuredatabricks.net,https://eastus.azureda
tabricks.net,https://eastus2.azuredatabricks.net,https://francecentral.azuredatabricks.net,https://japaneast.azuredatabricks.net,https://japanwest.azureda 
tabricks.net,https://koreacentral.azuredatabricks.net,https://koreasouth.azuredatabricks.net,https://northcentralus.azuredatabricks.net,https://northeurop
e.azuredatabricks.net,https://southafricanorth.azuredatabricks.net,https://southafricawest.azuredatabricks.net,https://southcentralus.azuredatabricks.net,
https://southeastasia.azuredatabricks.net,https://southindia.azuredatabricks.net,https://uaenorth.azuredatabricks.net,https://uksouth.azuredatabricks.net, 
https://ukwest.azuredatabricks.net,https://westeurope.azuredatabricks.net,https://westindia.azuredatabricks.net,https://westus.azuredatabricks.net,https:/ 
/westus2.azuredatabricks.net,https://us-west-2.cloud.databricks.com,https://us-west-1.cloud.databricks.com,https://us-east-1.cloud.databricks.com,https:// 
sa-east-1.cloud.databricks.com,https://eu-west-1.cloud.databricks.com,https://eu-west-3.cloud.databricks.com,https://eu-central-1.cloud.databricks.com,htt 
ps://ap-south-1.cloud.databricks.com,https://ap-southeast-2.cloud.databricks.com,https://ap-southeast-1.cloud.databricks.com,https://ap-northeast-2.cloud.
databricks.com,https://ap-northeast-1.cloud.databricks.com,https://ca-central-1.cloud.databricks.com" specified by the ValidateSet attribute. Supply an    
argument that is in the set and then try the command again.
Would you be able to resolve/advise please

**Comment by gbrueckl** [comment]
you can use `Set-DatabricksEnvironment -CustomApiRootUrl ... `

**Comment by hurtn** [comment]
Thank you
