### ISSUE TITLE
ServicePrincipal Authentication not compatible with Secrets API 

### ISSUE THREAD

**Issue by marvinbuss** [gbrueckl/Databricks.API.PowerShell#25]
If we authenticate using a Service Principal, the secret scope API does not work. We always get the following response:
`{"error_code":"TEMPORARILY_UNAVAILABLE","message":"Authentication is temporarily unavailable. Please try again later."}`

Workaround is to generate a PAT Token and reauthenticate using a PAT Token. This allows to create Databricks managed secret scopes.

Maybe you can add a note somewhere that this is not supported. Thanks! 👍

**Comment by gbrueckl** [comment]
yes, I am aware of this but it is actually a bug with the Databricks API and AAD authentication.
I informed MS and Databricks about it but it was not fixed yet.

as this PS module is just a wrapper for the API the cmdlet will fail if the API call fails. 

Dealing with this error is then up to the user (e.g. he can contact MS/Databricks support too)
Also it would be up to the user to implement the workaround you mentioned

**Comment by marvinbuss** [comment]
You are right, but it would be good to mention it somewhere, right?
I am not saying that you are supposed to fix this!
