### ISSUE TITLE
Add support for SQL Endpoint API

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#29]
Are they plans to add support for SQL Endpoint API :  https://docs.databricks.com/sql/api/sql-endpoints.html 
or https://docs.microsoft.com/en-us/azure/databricks/sql/api/sql-endpoints

Thank you.

**Comment by gbrueckl** [comment]
Yes, as soon as I find some time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gbrueckl** [comment]
alternatively you can also use the generic API call and specify the parameters on your own:
`Invoke-DatabricksApiRequest -Method GET -EndPoint "/2.0/sql/endpoints/"`

**Comment by gbrueckl** [comment]
just published version 1.5.0.0 which includes all cmdlets for SQL endpoints and SQL Query history
As I do not yet have access to the private preview I could not test them so please use them with caution!
Feedback is highly appreciated

**Comment by saldroubi** [comment]
Thank you. I’ll let you know if I encounter any problems. 

Sincerely,
Sam Al-Droubi

**Comment by saldroubi** [comment]
Is this in the GitHub repository or only in PSGallery?  I don't see the changes you made here.

**Comment by gbrueckl** [comment]
was in the PSGallery only but now it is also committed to this repo

**Comment by gbrueckl** [comment]
@saldroubi were you able to run some tests? 
I am still waiting to be granted access to the preview ...

**Comment by saldroubi** [comment]
No yet. But I plan to do so next week.  I’ll let you know.  

Sincerely,
Sam Al-Droubi

**Comment by saldroubi** [comment]
I am starting the test the SQLEndPointAPI.  
Get-DatabricksSQLEndpoint is not implemented correctly.  When I call it I get an error. 

Invoke-RestMethod: /Users/sameral-droubi/Downloads/git/Databricks.API.PowerShell/Modules/DatabricksPS/Public/General.ps1:85:13
Line |
  85 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error_code":"ENDPOINT_NOT_FOUND","message":"Endpoint not found for /2.0/sql/endpoints"}

I think the $requestMethod should be a **"Get" not a "Delete"**

Could you fix and put in PSGallery and I will test the rest.

**Comment by gbrueckl** [comment]
thanks for the hint, probably a copy&paste error
I fixed it and published it as v1.5.0.1
https://www.powershellgallery.com/packages/DatabricksPS/1.5.0.1

**Comment by gbrueckl** [comment]
closing this issue after running my own tests 
and due to no further feedback
