### ISSUE TITLE
Databricks New Job Create using PowerShell

### ISSUE THREAD

**Issue by harshadaji** [gbrueckl/Databricks.API.PowerShell#3]
I am working with a PowerShell Module for Databricks – DatabricksPS.  (https://www.powershellgallery.com/packages/DatabricksPS/0.5.0.0)
 
I couldn’t find way to create a new job and run it with its Job ID.
 
Please let me know if anyone has tried creating a Databricks new job and running it using PowerShell?
 
Note : I tried using the New-DatabricksJobRun Cmdlet from the DatabricksPS module but that didn’t help.

**Comment by gbrueckl** [comment]
seems like I missed the cmdlet "New-DatabricksJob" that would use this API: https://docs.databricks.com/api/latest/jobs.html#create
I will add it and update you here

**Comment by harshadaji** [comment]
Hi Gerhard,

Yes, Thanks!

**Comment by gbrueckl** [comment]
just published a new version to the PowerShell gallery (0.6.0.0)
https://www.powershellgallery.com/packages/DatabricksPS/0.6.0.0
which now also contains the Add-DatabricksJob cmdlet
I ran some basic tests and it seems to work but I am happy for any feedback!

**Comment by gbrueckl** [comment]
There is also a cmdlet called "Invoke-DatabricksApiRequest" which allows you to run any API request so you can build the request on your own according to the docs
