### ISSUE TITLE
Add ClusterName parameter to the Get-DatabricksCluster function

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#30]
Could Get-DatabricksCluster be enhanced so that it accepts a cluster name not just an cluster id?

**Comment by gbrueckl** [comment]
technically, yes, this would of course work
however, this cmdlet is supposed to be a wrapper for the Databricks REST API which does not support getting a cluster by name
so for now, this will also not be added to this module

alternatively you can use 
`Get-DatabricksCluster | Where-Object { $_.cluster_name -eq "my cluster name" }`

please be aware that cluster name are not necessarily unique!
