### ISSUE TITLE
Update-DatabricksCluster issues (Azure)

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#31]
It does not seem that the the cmdlet is implemented to pass a cluster_id to update the cluster attributes.

For example 

Update-DatabricksCluster  -ClusterID "0203-171839-jxtks760" -MinWorkers 2 -MaxWorkers 8     
Generates the following error.

Update-DatabricksCluster: Cannot bind positional parameters because no names were given.

Also tried to pipeline a cluster object received from Get-DatabricksCluster 
as follows:

 $clusterObj | Update-DatabricksCluster   -MinWorkers 2 -MaxWorkers 8

This runs but does change the MinWorkers and MaxWorkers. 

So far I have not been able to make this cmdlet work in any combination I tried. 

When I looked at the cmdlet help and code it does not seem that the pipeline is implemented on any of the parameter so pipelining the object will not work, I suppose.

**Comment by gbrueckl** [comment]
The first should actually work, I will check tomorrow

The second will currently not work as not all Cmdlets support pipelining yet. Will add it when I fix the first issue

Thanks for the feedback!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gbrueckl** [comment]
just fixed the issues
One of the problems is that the parameters SparkVersion and NodeType are actually mandatory by the API, so you would always need to include those 
There is also the `Resize-DatabricksCluster` cmdlet - however, this only works if the cluster is in RUNNING state

so probably the best to update an existing cluster is by using a ClusterObject like in your second example which works now:
`$clusterObj | Update-DatabricksCluster -MinWorkers 2 -MaxWorkers 8`

**Comment by saldroubi** [comment]
Thank you.  I think it seems to be working now.  However, there is an issue.  If the cluster is in a "restarting" state the 
Update-DatabricksCluster will generate this error:

Line |
  85 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error_code":"INVALID_STATE","message":"Cluster 0204-194049-whirl976 is in unexpected state Restarting."}

Maybe it would be good to terminate the cluster and do the update and restart it if it is in this state.   Could this be part of the implementation?  It seems to be consistent with what the comments say in the code.

**Comment by gbrueckl** [comment]
Well, that error message comes from the API directly and has nothing to do with the PS module. You can check the state of the cluster upfront on your own but that is up to you then.
This module only acts as a wrapper for the REST API

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
