### ISSUE TITLE
Create job with cluster policy?

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#33]
Hi Gerhard, 

I created a cluster policy.  Is there a way to create a job using Add-DatabricksJob  cmdlet and reference this job policy as a parameter?  Also, I want to use a job cluster not an All-Purpose cluster.  In other words, there is no cluster ID to pass.  The job cluster will be created when the job is scheduled to run.   This on Azure platform.

Thank you so much.

**Comment by gbrueckl** [comment]
according to the official docs it is not possible to supply a `policy_id  when creating a Job
https://docs.databricks.com/dev-tools/api/latest/jobs.html#runs-submit (or `New-DatabricksJobRun`)

however, you can give it a try and see if it still works when you inject the policy_id into the REST call using `Invoke-DatabricksApiRequest`

in general, whenever you specify a `cluster_id`, you are talking about an existing [all-purpose] cluster but a job cluster.
job-clusters are created on demand for each individual job-run so also the cluster_id for them is different every time. you always need to the whole cluster definition https://docs.databricks.com/dev-tools/api/latest/jobs.html#jobsclusterspecnewcluster

**Comment by gbrueckl** [comment]
it is even stated in the docs:
_To create a job or submit a run with a new cluster using a policy, set policy_id to the policy ID:_
https://docs.databricks.com/dev-tools/api/latest/clusters.html#examples

so to use a job-cluster with a cluster policy, you need to overwrite/set the property `policy_id` of `-NewClusterDefinition`
