### ISSUE TITLE
Getting workspace ID / Cluster connection JDBC/ODBC information

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#34]
Is there a way to get the the cluster workspace ID.  When you connect to the cluster using the web interface it is usually at the end of the url that looks something similar to this on Azure:

https://adb-14128623206503122.5.azuredatabricks.net/?o=3412862326502525

It is what follows o=<workspaceID>

You can also find this embedded in the cluster "Advanced Options" under JDBC/ODBC tab under HTTP path.  
I was not able to find a cmdlet that gives this information.  Can this be added?
 

Thank you

**Comment by gbrueckl** [comment]
Databricks provides no REST API that I would be aware of to get the organization id so I also cannot provide this via the module.

May I ask what you need it for?

**Comment by saldroubi** [comment]
We have many workspaces on Azure.   Sometimes we are asked to provide all the workspace URLs/IDs  to technical support so I want write a script that does that.  I found a way to do it here it is:
  $workspaceResource = Get-AzResource `
        -ResourceType "Microsoft.Databricks/workspaces" `
        -Name $WorkspaceName  `
        -ResourceGroupName $ResourceGroupName `
        -ExpandProperties

        $url = "http://" + "$($workspaceResource.Properties.workspaceUrl)" + "/?o=" + "$($workspaceResource.Properties.workspaceId)"

Thank you.
