### ISSUE TITLE
Add functionality to manage endpoint permissions

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#35]
Hello,

Could you add a way to manage the endpoint permission.  This link https://docs.databricks.com/sql/user/security/access-control/sql-endpoint-acl.html describes the API to Manage SQL Endpoint permissions.  I don't think this is implemented yet.  Could this be added?

Thank you
Sam Al-Droubi

**Comment by gbrueckl** [comment]
yes, will definitely add this in the near future (as soon as I find some time)
untilt then, you can use the `Invoke-DatabricksApiRequest` and manually build your request according the the docs

**Comment by gbrueckl** [comment]
just published v1.9.9.0: 
- Added support for SQL endpoints to the `*-DatabricksPermissions` cmdlets as described here [SQL Endpoint Permissions](https://docs.databricks.com/sql/user/security/access-control/sql-endpoint-acl.html#manage-sql-endpoint-permissions-using-the-api).
