### ISSUE TITLE
Get-DatabricksSCIMGroup not returning the group id

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#36]
When calling Get-DatabricksSCIMGroup -Format List I am not getting the group ID in the output.  Could this be fixed?  Is there a workaround for now to get the group id until this if fixed?

I am on Azure platform. 

Thank you
Sam Al-Droubi

**Comment by gbrueckl** [comment]
Hi Sam,

the whole module acts as a wrapper for the Databricks REST API and just returns what the original REST API returns. This behavior is not going to change.
I ran some tests against my system and it is actually returning group ids in the field `id`:
```
    {
        "entitlements":  [
                             {
                                 "value":  "allow-cluster-create"
                             }
                         ],
        "displayName":  "TestGroup",
        "groups":  [

                   ],
        "id":  "5622540116035711"
    }
```

can you please check again. If you still do not see the IDs you are looking for, you can try `-Format Raw` which will give you the exact output as it was returned by the underlying Databricks REST API

**Comment by gbrueckl** [comment]
closing due to missing feedback
