### ISSUE TITLE
Raise instruction in Add-PropertyIfNotExists

### ISSUE THREAD

**Issue by dannyboodmann** [gbrueckl/Databricks.API.PowerShell#4]
The function Add-PropertyIfNotExists contains the instructions "raise" that  is not recognized as the name of a cmdlet... ; should it be a throw? is it supposed to be a write-warning?

The error is annoying: I'm creating a new cluster with Add-DatabricksCluster with few basic parameters and the "raise" is called several times,

**Comment by gbrueckl** [comment]
just fixed with version 7.0.1

**Comment by gbrueckl** [comment]
sorry, the previous fix did not work - please try version 7.0.2
