### ISSUE TITLE
Not able to get output value of databricks job in console

### ISSUE THREAD

**Issue by sreekanth-reddy** [gbrueckl/Databricks.API.PowerShell#40]
When i am trying to use this command "Get-DatabricksJobRun -JobID 3" in the state section of output its not showing the output value of the databricks job.
![image](https://user-images.githubusercontent.com/45034128/116408673-ba37c800-a850-11eb-9d07-20c805b44d80.png)

**Comment by gbrueckl** [comment]
thats the original output from the Databricks REST API 
the module can only provide the information that is returned from the underlying API
if there is no value for `state_message` then I cannot be shown

what value would you expect?

**Comment by sreekanth-reddy** [comment]
> thats the original output from the Databricks REST API
> the module can only provide the information that is returned from the underlying API
> if there is no value for `state_message` then it cannot be shown
> 
> what value would you expect?

I am just using the below sample code in notebook and created job on top of this notebook

**dbutils.widgets.text('inputTest', '', label = "Input")

printParam = dbutils.widgets.get("inputTest")
print("Notebook Triggerd! Input param : " + printParam)**

and calling this job using powershell
![image](https://user-images.githubusercontent.com/45034128/116434044-b06d8f00-a867-11eb-8853-b2a87988a405.png)

So I need to get output as whatever value i  am passing as parameter i.e., sreekanth

**Comment by sreekanth-reddy** [comment]
I mean i want to get output value
For suppose a =2 and b=3  
c = a + b 
c =5 
I need 5 as output value when i pass two parameters a and b

**Comment by gbrueckl** [comment]
you can try `Export-DatabricksJobRun` or `Get-DatabricksJobRunOutput`
both take the `job_run_id` that is returned by `Start-DatabricksJob` as an input parameter

**Comment by sreekanth-reddy** [comment]
Its not giving the output again, i tried it 
![image](https://user-images.githubusercontent.com/45034128/116463157-fdf9f400-a887-11eb-8fd6-2692dcb423fd.png)

**Comment by gbrueckl** [comment]
Can you run
Get-DatabricksJobRunOutput -JobRunID 9 | ConvertTo-Json -Depth 10
to get the full output visualized please

But again, if the API doesnt not provide that information, the module/cmdlets cannot show it

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by gbrueckl** [comment]
please also have a look here https://docs.databricks.com/dev-tools/api/latest/jobs.html#runs-get-output
and maybe consider using `dbutils.notebook.exit("myReturnValue")` as described here https://docs.databricks.com/notebooks/notebook-workflows.html#notebook-workflows-exit

**Comment by sreekanth-reddy** [comment]
Ok will check and get back

**Comment by gbrueckl** [comment]
could you finally resolve this?
if yes, I would like to close this ticket

**Comment by gbrueckl** [comment]
closing this due to missing feedback - assuming it is fixed now
