### ISSUE TITLE
Why the warning 

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#42]
I am getting a warning when I pipe a cluster object to Update-DatabricksCluster.

Code:  $clusterObj | Update-DatabricksCluster -NumWorkers $NumWorkers -SparkVersion $SparkVersion -NodeTypeId 

Here is the warning:  WARNING: The cluster_id was provided via parameter -ClusterID and also as part of -ClusterObject. Finally the value from -ClusterID will be used!

It is being caused by this code statement in the function. 
if ($ClusterID -and $parameters.ContainsKey("cluster_id")) {
        Write-Warning "The cluster_id was provided via parameter -ClusterID and also as part of -ClusterObject. Finally the value from -ClusterID will be used!"
      }

I am not sure why this warning is being generated.   Piping the object I got from Get-DatabricksCluster shouldn't generate this warning, I don't think.

**Comment by gbrueckl** [comment]
you are absolutely right, the warning should not happen
it is fixed now with 19.5.1. which is also already live in the gallery

btw, to resize a running cluster, you can also use the `Resize-DatabrickCluster` cmdlet

**Comment by gbrueckl** [comment]
does this work now?
I would like to close the ticket then

**Comment by saldroubi** [comment]
Give me a few days to test this.  I am pretty busy this week.

**Comment by saldroubi** [comment]
This is working correctly now without the warning.  So it is fixed.

**Comment by saldroubi** [comment]
This is working correctly now without the warning. So it is fixed.
