### ISSUE TITLE
Update-DatabricksJob error

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#43]
I am trying to use Update-DatabricksJob but I get an error when I try to update the runtime version value for example. 

I am using existing settings of a certain job and then just changing the spark_version from existing 7.3 to 8.4 but I get an error.  Here is what I tried:

$testJob = Get-DatabricksJob -JobID 27

$testJob.settings.new_cluster.spark_version="8.4.x-scala2.12"

$updatedSettings = $testJob.settings

Update-DatabricksJob -JobID 27 -NewSettings $updatedSettings

I get this error:

Invoke-RestMethod: /Users/sameral-droubi/.local/share/powershell/Modules/DatabricksPS/1.9.5.0/Public/General.ps1:85:13
Line |
  85 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error_code":"INVALID_PARAMETER_VALUE","message":"Cluster validation error: Validation failed for spark_version, the value must be 7.3.x-scala2.12 (is \"8.4.x-scala2.12\")"}

When I looked at the Update-DatabricksJob function code I noticed that the $apiEndPoint on line 364 is set to reset not update.  Is this correct?
 
$apiEndpoint = "/2.0/jobs/reset"

According to API I think an update is needed: https://docs.databricks.com/dev-tools/api/latest/jobs.html#jobsjobsserviceupdatejob 

FYI, the job I am trying to update was created with a cluster policy. 

So how do I update certain settings of a job?

Thank you

**Comment by saldroubi** [comment]
I noticed that the "reset" API function is useful https://docs.databricks.com/dev-tools/api/latest/jobs.html#reset
If the job is created using a cluster policy and then you modify the policy the job does not pick those changes unless you call reset.  So this is what I want.  I think there should either two functions one to rest the job and one to make edits to existing configuration.  What do you think?

**Comment by gbrueckl** [comment]
so the original idea was to always replace the job - hence the call to the reset-API
this was under the assumption, that you can simply change the job as you did in your example:
1. Get the current job
2. change the settings you want
3. Update/reset the job with the full definition

have you tried the update-API with your change? will it still fail/complain about the spark_version as your job was created with a policy?

**Comment by saldroubi** [comment]
FYI

I found a workaround using your update API function. 
1- Get current job settings
2- remove policy_id from settings 
3- update current job without the policy id
4- update again with same policy id

This will force the policy changes to propagate to the job and does not throw and error.

**Comment by gbrueckl** [comment]
great it works this way!

alternatively you can also built the required API requests on your own:
```
$body = @{
	"job_id" =  1
	"new_settings" = @{
		"existing_cluster_id" = "1201-my-cluster"
		"email_notifications" = @{
			"on_start" = @("someone@example.com")
			"on_success" = @()
			"on_failure" = @()
		}
	}
	"fields_to_remove" = @("libraries")
}
		
$result = Invoke-DatabricksApiRequest -Method "POST" -EndPoint "/2.0/jobs/update" -Body $body
```

and POST it to the API-endpoint

**Comment by gbrueckl** [comment]
but I will probably extend the current Update-DatabricksJob so you can pass in -FieldsToRemove and -UpdateSettings is alternative to -NewSettings
depending on what you use, the update or reset API will be called

**Comment by saldroubi** [comment]
Yeah, I think it will be really useful to update the function as you described above.

**Comment by gbrueckl** [comment]
just published the fix
```
$upd = @{ "timeout_seconds" = 1
	 "max_retries" = 2}

$jobs[0] | Update-DatabricksJob -UpdateSettings $upd -FieldsToRemove @("email_notifications") -Verbose
```

this should work now

**Comment by gbrueckl** [comment]
do you have an update for me on this?
can I close the issue?

**Comment by gbrueckl** [comment]
close due to missing updates - assuming it is working now as expected
