### ISSUE TITLE
Error when calling Get-DatabricksSQLHistory 

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#45]
Calling Get-DatabricksSQLHistory with a sql endpoint id generates an error. Here is an example:

Get-DatabricksSQLHistory -SQLEndpointIds "39b3d2a4822a1bb8"

**Get-DatabricksSQLHistory: The alias "user_ids" is declared multiple times.**

**Comment by gbrueckl** [comment]
thanks for reporting
I just fixed it with 1.9.6.0
please give it a try and update this issue

**Comment by saldroubi** [comment]
This error went away so I will close this issue.

**Comment by saldroubi** [comment]
Error went away.
