### ISSUE TITLE
Get-DatabricksSQLHistory -max_results parameter not working

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#46]
Example:

Get-DatabricksSQLHistory -max_results 1

always returns a result of 100 regardless of what the function is passed. 

>$a = Get-DatabricksSQLHistory -max_results 1

>$a.res.Count

100

**Comment by gbrueckl** [comment]
hmm, you are right but it seems like a but to me with the underlying Databricks API or the docs
If I build the API request as described in the docs it does not work :/

**Comment by saldroubi** [comment]
I built the body myself and used Invoke-DatabricksApiRequest and I am getting the expected max results as follows:

$requestMethod = "GET"
$apiEndpoint = "/2.0/sql/history/queries"

$SQLEndpointIds=("29a4d2n4842l0bv8")

$parameters = @{max_results = 1000000}

$result = Invoke-DatabricksApiRequest -Method $requestMethod -EndPoint $apiEndpoint -Body $parameters

$result.res.count

**2993**

When I run the above with verbose flag I get the below.  So I am thinking API is probably working ok and something wrong with the function.  What do you think?


Name                           Value
----                           -----
Content-Type                   application/json
Authorization                  Bearer dapiXXX


Body: 

Name                           Value
----                           -----
max_results                    1000000


GET https://adb-6137959104544159.19.azuredatabricks.net/api/2.0/sql/history/queries?max_results=1000000 with 0-byte payload
received -byte response of content type application/json
Content encoding: utf-8
Response: {
  "next_page_token": "CkgKJGU2MDNjNjEwLWNlOWUtNDg0OS04OWFlLWZhNmZkMWNmNjljYxDp142SsC8Y9I6wjcvIpQ8iEDI5ZTNkMmU0ODQyYTBiYjgYsRc=",
  "res": [
    {
      "query_id": "3676ce5f-bc96-4cf8-952b-a3e74c921797",
      "status": "FINISHED",
      "query_text": "Listing tables 'catalog : null, schemaPattern : %, tableTypes : null, tableName : %'",
      "query_start_time_ms": 1630422701781,
      "execution_end_time_ms": 1630422702087,
      "user_id": 8609471084103540,
      "user_name": "fd2bde31-e603-4645-a012-881dc0e5896a",
      "endpoint_id": "29e3d2e4842a0bb8",
      "rows_produced": 259,
      "lookup_key": "CiQzNjc2Y2U1Zi1iYzk2LTRjZjgtOTUyYi1hM2U3NGM5MjE3OTcQ1a2Q5rkvGhAyOWUzZDJlNDg0MmEwYmI4IPSOsI3LyKUP",
      "executed_as_user_id": 8609471084103540,
      "executed_as_user_name": "fd2bde31-e603-4645-a012-881dc0e5896a"
    },
...etc

**Comment by gbrueckl** [comment]
it gets a bit more complex if you add the filter_by clause as this does not work with the Body-parameter of the Invoke-RestRequest

honestly, during my tests I used max_results < 10 and it always returned all of them - I need to generate 100+ queries so I can properly test this also with values > 100 (the default)

**Comment by gbrueckl** [comment]
ok, after some investigation, I found the root-cause.
In Windows PowerShell which is based on the .NET Framework it is not supported to send a GET request with a body
However, in PowerShell CORE which is based on the .NET Core Framework this is supported
https://github.com/dotnet/runtime/issues/25485

I changed the cmdlet to print a warning if executed on Windows PowerShell including those details and also saying that everything under `filter_by` will be ignored

I see two options for you:
- Use PowerShell CORE -DatabricksPS fully supports it
- stick with Windows PowerShell, get all results and filter them on the client-side. The API returns the most recent queries first

**Comment by saldroubi** [comment]
I use Powershell core and I think Windows Powershell is getting desupported, correct?

**Comment by saldroubi** [comment]
Did you publish a new version for this fix?

**Comment by gbrueckl** [comment]
Yes, 1.9.6.1

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by saldroubi** [comment]
Never mind I see that you have version 1.9.6.1
