### ISSUE TITLE
Get Help for Set-DatabricksPermissions returns notes for Get-DatabricksPermissions

### ISSUE THREAD

**Issue by itconsultantonthedge** [gbrueckl/Databricks.API.PowerShell#47]
Hi,
When running the command Get-Help Set-DatabricksPermissions -full, you get details for Get-DatabricksPermissions in the examples, and some wording around retrieve permission, rather that 'set' 

NAME
    Set-DatabricksPermissions
    
SYNOPSIS
    Sets permissions for the objects inside the Databricks workspace.
    
    
SYNTAX
    Set-DatabricksPermissions [-ObjectID <String>] -ObjectType <String> -AccessControlList <Object[]> [-Overwrite] [-Raw] [<CommonParameters>]
    
    Set-DatabricksPermissions -ObjectID <String> -WorkspaceObjectType <String> -AccessControlList <Object[]> [-Overwrite] [-Raw] [<CommonParameters>]
    
    Set-DatabricksPermissions -ClusterID <String> -AccessControlList <Object[]> [-Overwrite] [-Raw] [<CommonParameters>]
    
    Set-DatabricksPermissions -JobID <String> -AccessControlList <Object[]> [-Overwrite] [-Raw] [<CommonParameters>]
    
    Set-DatabricksPermissions -InstancePoolID <String> -AccessControlList <Object[]> [-Overwrite] [-Raw] [<CommonParameters>]
    
    
DESCRIPTION
    Sets permission for the objects inside the Databricks workspace.
    Official API Documentation: https://docs.databricks.com/dev-tools/api/latest/permissions.html
    

PARAMETERS
    -ObjectID <String>
        The unique ID of the object for which you want to retrieve the permission(s). e.g. a cluster_id if ObjectType = Cluster
        
        Required?                    false
        Position?                    named
        Default value                
        Accept pipeline input?       true (ByPropertyName)
        Accept wildcard characters?  false
        
    -ObjectType <String>
        The type of the object for which you want to retrieve the permission(s). e.g. Cluster, Job, Directory, ...
        
        Required?                    true
        Position?                    named
        Default value                
        Accept pipeline input?       true (ByPropertyName)
        Accept wildcard characters?  false
        
    -ClusterID <String>
        The unique ID of the cluster for which you want to retrieve the permission(s).
        
        Required?                    true
        Position?                    named
        Default value                
        Accept pipeline input?       true (ByPropertyName)
        Accept wildcard characters?  false
        
    -JobID <String>
        The unique ID of the job for which you want to retrieve the permission(s).
        
        Required?                    true
        Position?                    named
        Default value                
        Accept pipeline input?       true (ByPropertyName)
        Accept wildcard characters?  false
        
    -InstancePoolID <String>
        The unique ID of the instance pool for which you want to retrieve the permission(s).
        
        Required?                    true
        Position?                    named
        Default value                
        Accept pipeline input?       true (ByPropertyName)
        Accept wildcard characters?  false
        
    -WorkspaceObjectType <String>
        The type of the workspace item for which you want to retrieve the permission(s). The workspace item itself is specified using -ObjectID.
        
        Required?                    true
        Position?                    named
        Default value                
        Accept pipeline input?       true (ByPropertyName)
        Accept wildcard characters?  false
        
    -AccessControlList <Object[]>
        
        Required?                    true
        Position?                    named
        Default value                
        Accept pipeline input?       true (ByValue, ByPropertyName)
        Accept wildcard characters?  false
        
    -Overwrite [<SwitchParameter>]
        
        Required?                    false
        Position?                    named
        Default value                False
        Accept pipeline input?       false
        Accept wildcard characters?  false
        
    -Raw [<SwitchParameter>]
        Can be used to retrieve the raw output of the API call. Otherwise an object with all the permissions is returned.
        
        Required?                    false
        Position?                    named
        Default value                False
        Accept pipeline input?       false
        Accept wildcard characters?  false
        
    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see 
        about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216). 
    
INPUTS
    
OUTPUTS
    
    -------------------------- EXAMPLE 1 --------------------------
    
    PS C:\>Get-DatabricksPermissions -ObjectType "CLUSTERS" -ObjectID "1202-211320-brick1"
    
    
    
    
    
    
    -------------------------- EXAMPLE 2 --------------------------
    
    PS C:\>Get-DatabricksPermissions -ObjectType "JOBS" -ObjectID "1" -Raw
    
    
    
    
    
    
    -------------------------- EXAMPLE 3 --------------------------
    
    PS C:\>(Get-DatabricksCluster)[0] | Get-DatabricksPermissions

**Comment by gbrueckl** [comment]
Thansk for the hint!
I just updated the module (1.9.6.2) to update the docs
