### ISSUE TITLE
Workspace permissions - How to set using API?

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#49]
Hello,

I am trying to set workspace settings programmatically.   
As shown in attached file the UI allows you to change settings for entire workspace.  
I was able to set **Personal Access Tokens** using  Set-DatabricksPermissions -ObjectType "TOKENS" -AccessControlList $all
but I am not able to find how to do this in the module or the API itself.  

Particularly I am trying to enable these: 

- Workspace Visibility Control:  Enabled
- Cluster Visibility Control: Enabled
- Job Visibility Control: Enabled
- DBFS File Browser: Enabled
 
![workspace_permissions](https://user-images.githubusercontent.com/16247245/160714535-4536305f-d4e0-49df-a37b-9b63791e69c4.jpg)

Is this doable?

Thank you

**Comment by gbrueckl** [comment]
I just published v1.9.9.3 which allows you to do this:
```
Set-DatabricksWorkspaceConfig -CustomConfig @{
	"enforceWorkspaceViewAcls" = "true"
	"enforceClusterViewAcls" = "true"
	"enableJobViewAcls" = "true"
	"enableDbfsFileBrowser" = "true"
}
```

this `-CustomConfig` basically supports any dictionary that you want to pass to `/api/2.0/workspace-conf`
if the key or value is not valid, it will throw an error

to get the keys from above I used Fiddler to track what the UI is sending
The workspace-config API itself is not documented anywhere officially, but it is referenced in some other API definitions so there is no guarantee that everything works as expected

happy to hear some feedback from you though!

**Comment by saldroubi** [comment]
This awesome.  Thank you. I wonder why this API is not published at Databricks website.  I didn't know about Fiddler.  Thank you for that information. It is however not a free tool.

**Comment by gbrueckl** [comment]
I think it is free but you may need to register - anyway, I think/hope I added all settings :)

**Comment by saldroubi** [comment]
Thank you very much for this package.  You work is a great contribution which mages DBR workspace management much easier.

**Comment by gbrueckl** [comment]
closing as it was implemented in a previous version
