### ISSUE TITLE
module does not get imported in automation account runbooks

### ISSUE THREAD

**Issue by ppalucha** [gbrueckl/Databricks.API.PowerShell#5]
Hi,
I'm trying to use databricksPS to create a runbook in Azure Automation Account. The module is imported into automation account, Ctrl-Space gives me cmdlets and parameters, but while actually trying to start any runbook, I get the message like

The term 'Set-DatabricksEnvironment' is not recognized as the name of a cmdlet, function, script file,...

When running runbook in Verbose mode, it prints names of all imported cmdlets, but databricksPS is *not* listed there. However, it works when I import module explicitly, using "Import-Module". So I guess there's either something wrong with module metadata, or it's due to use on unapproved verbs for module's cmdlets.

**Comment by gbrueckl** [comment]
I just ran  a test and it worked just fine for me with the following code:
`
Import-Module DatabricksPS -Verbose

$accessToken = "dapi12341234123412341234"
$apiUrl = "https://westeurope.azuredatabricks.net"

Set-DatabricksEnvironment -AccessToken "$accessToken" -ApiRootUrl "$apiUrl" -Verbose

Test-DatabricksEnvironment -Verbose
`

Did you add the Module via the gallery or via import?
I used the gallery and it worked

**Comment by ppalucha** [comment]
Hi, 
The issue is that you should not need to explicitly run "Import-Module". You can run cmdlets from any other module without "Import-Module" - necessary modules are discovered and loaded automatically. It doesn't work for DatabricksPS, adding "Import-Module" is a workaround. 
Regards
Pawel

**Comment by gbrueckl** [comment]
I assume this is because the cmdlets are added dynamically once the module is imported as I have chosen a dynamic approach instead of a static one where I would need to update the .psd1 file with every new function I add

For now, I ask you to go with the workaround using Import-Module
I may add static references using FunctionsToExport in .psd1 in the future

**Comment by gbrueckl** [comment]
this has been fixed with the latest release - please update the module and rerun the test

**Comment by gbrueckl** [comment]
just tested on my own and it is working now
