### ISSUE TITLE
Set-DatabricksEnvironment using AAD Username/password?

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#55]
I am trying to setup the environment using username/password but I am confused about the client id?
In you example on https://github.com/gbrueckl/Databricks.API.PowerShell#azure-active-directory-aad-usernamepassword 
You set client id as so:

$clientId = 'db00e35e-1111-2222-3333-c8cc85e6f524'

What is this referring to?  I this the service principal client id or is the the actual AD user client id. I am not sure how to get this for a use.  What if I am not using a service principal/App?  Is the client ID same as object ID of an AAD user?
Is there a way to get the client ID using PowerShell?

Thank you.

**Comment by gbrueckl** [comment]
for username/password authentication to work you first need to create an app registration in your AAD tenant as described here:
https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/app-aad-token#configure-an-app-in-azure-portal
which will also provide the `client_id` to you

**Comment by saldroubi** [comment]
I am not using "-UsingAzContext" option which you added implemented and it is working fine for my needs. 

Thank you.

**Comment by gbrueckl** [comment]
for later reference, i guess this is what you were looking for:
https://github.com/gbrueckl/Databricks.API.PowerShell#azure-active-directory-aad-usernamepassword
