### ISSUE TITLE
Implement Queries, Dashboards, and Alerts API 2.0

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#58]
Could you please implement this API.  I would to use it to run grants using the API.

For example:  GRANT ALL PRIVILEGES ON TABLE forecasts TO finance; 

https://learn.microsoft.com/en-us/azure/databricks/sql/api/queries-dashboards

I looked through the API and it is not clear to me that you can run grant statements through it.  Maybe it only permits Select Statements.  Can you tell?

Thank you.

**Comment by gbrueckl** [comment]
Its not for granting permissions but you could this via the command execution/context  API which is already implemented

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: saldroubi ***@***.***>
Sent: Saturday, September 24, 2022 2:12:34 AM
To: gbrueckl/Databricks.API.PowerShell ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gbrueckl/Databricks.API.PowerShell] Implement Queries, Dashboards, and Alerts API 2.0 (Issue #58)


Could you please implement this API. I would to use it to run grants using the API.

For example: GRANT ALL PRIVILEGES ON TABLE forecasts TO finance;

https://learn.microsoft.com/en-us/azure/databricks/sql/api/queries-dashboards

I looked through the API and it is not clear to me that you can run grant statements through it. Maybe it only permits Select Statements. Can you tell?

Thank you.

**Comment by saldroubi** [comment]
I am trying to do this against a SQLWarehouse endpoint.  I want to run grants.  This  did not work when I tried to create a context. 
I want to run something like this statement $mySql = "GRANT ALL PRIVILEGES ON TABLE forecasts TO finance;" 

When I run this statement I get an error.  Not that the ID if for a SQLWarehouse Endpoint.
$SQLContext = Get-DatabricksExecutionContext -ClusterID "6abb7b5b9f83a484" -Language "sql"

ame                           Value
----                           -----
Content-Type                   application/json
Authorization                  Bearer XXXXXXXXXXXXXXXNiIsIng1dCI6IjJaUXBKweeM1VwYasdfWVhZR2asRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQ…


VERBOSE: Body: 
{
  "clusterId": "6abb7b5b9f83a484",
  "language": "sql"
}
VERBOSE: POST with 58-byte payload
VERBOSE: received 74-byte response of content type application/json
Invoke-RestMethod: /Users/saldroubi/.local/share/powershell/Modules/DatabricksPS/1.9.9.14/Public/General.ps1:96:13
Line |
  96 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error":"ClusterNotFoundException: Cluster not found: 6abb7b5b9f83a484"}

**Comment by gbrueckl** [comment]
I am quite sure this needs to be run against a regular endpoint and not a SQLWarehouse endpoint 
the Command Execution API was created years before the SQL Warehouses so the will not work

**Comment by saldroubi** [comment]
I run this in a SQL window using the SQLWarehouse endpoint so I would like for a way to run this programmatically instead of using the UI.  That was my initial request.

**Comment by gbrueckl** [comment]
sure, but just because it is working in the SQL window in the UI does not necessarily mean it is also working with an API that was built before the SQL Warehouse endpoints even existed.

I am afraid your only option to run it programmatically is to spin up a regular cluster and run your SQL command against it using the Command Execution API.

this module is just a wrapper for the API provided by Databricks - if the underlying API does not offer this functionality, this module also cannot provide it, sorry
