### ISSUE TITLE
Get-DatabricksInstancePools Error

### ISSUE THREAD

**Issue by mcgrawd** [gbrueckl/Databricks.API.PowerShell#59]
When calling Add-DatabricksCluster, I am getting the following error:

Get-DatabricksInstancePools : The term 'Get-DatabricksInstancePools' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\v-mcgrawd\Documents\WindowsPowerShell\Modules\DatabricksPS\1.9.9.13\Public\InstancePoolsAPI.ps1:262 char:55
+ ... alues = (Get-DynamicParamValues { Get-DatabricksInstancePools -List } ...
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-DatabricksInstancePools:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Looking at instancePoolsAPI.ps1, I see that there is a Get-DatabricksInstancePool function but there is no Get-DatabricksInstancePools funtion.  Is this just a typo on the function name?

**Comment by gbrueckl** [comment]
that was definitly a typo - but may I ask what tool you use to write your PowerShell code?
as it never popped up on my machine and I am developing in VSCode
I also ran a quick test in PowerShell ISE and it also worked there

so I am really curious where you experience this issue

**Comment by mcgrawd** [comment]
Thanks for the quick response!  I installed v1.9.9.15 and confirmed that the issue has been fixed. 

FYI, I am using PowerShell ISE on a server for testing.  I'm not an admin on the server, so I installed the DatabricksPS module using -Scope CurrentUser
```
    Directory: C:\Users\<myuserid>\Documents\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands                                                                           
---------- -------    ----                                ----------------                                                                           
Script     1.9.9.15   DatabricksPS                        {Get-DatabricksClusterPolicy, Add-DatabricksClusterPolicy, Remove-DatabricksClusterPolic...
```
BTW, Great job on this module!  It is really a big time saver.  
I am able to use it in an Azure DevOps pipeline with ARM Service Connection authentication (no PAT required) which works very well.

**Comment by gbrueckl** [comment]
weird, PowerShell ISE also worked on my machine with the old code

anyway - if it is working now and the code is obviously fixed - I will close this issue

**Comment by mcgrawd** [comment]
OK.  Thanks.
FYI, try the following commands.  These are the commands I was using when I was getting the error that you fixed.
```
Add-DatabricksCluster -ClusterName "WDMTest"
Add-DatabricksCluster -NumWorkers 2 -ClusterName "WDMTest"
```
With v1.9.9.15, the first command  gives a "Parameter set cannot be resolved using the specified parameters" error.  
The second command gives a 400 error even with v.1.9.9.15:
```
PS C:\Users\<userid>> Add-DatabricksCluster -NumWorkers 2 -ClusterName "WDMTest2"

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\<userid>\Documents\WindowsPowerShell\Modules\DatabricksPS\1.9.9.15\Public\General.ps1:96 char:13
+ ...   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 ```
That's when I realized that I was missing some parameters so I checked the examples.  
This is the command that I tested and worked with v1.9.9.15: 
```
   Add-DatabricksCluster -NumWorkers 2 -ClusterName "WDMTest" -SparkVersion "10.4.x-scala2.12" -NodeTypeId 'Standard_DS3_v2'
```
I hope that helps.

**Comment by gbrueckl** [comment]
so there are some mandatory parameters which you always need to supply 
some are enforced in the cmdlet from this module, some are enforced by the API only
in the second case (as also in your second example), you should get an error message like this:
![image](https://user-images.githubusercontent.com/11884402/197212481-43f6aa8b-0519-4e59-8be7-7af6c0813022.png)

your last command supplies all parameters so it is working succeeding
