### ISSUE TITLE
Create Clusters Custom Tag property type error...

### ISSUE THREAD

**Issue by robertwcyu** [gbrueckl/Databricks.API.PowerShell#6]
Get error when using Custom tag...

Invoke-RestMethod : {"error_code":"MALFORMED_REQUEST","message":"Could not parse request object: Expected object for
field custom_tags, found STRING"}
At C:\Program Files\WindowsPowerShell\Modules\DatabricksPS\0.8.0.1\Public\General.ps1:53 char:12
+ ...   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by gbrueckl** [comment]
there was an issue with the parameter type - it was string but should be hashtable - this is fixed now
you can use it as follows:
`$tags = @{
		"MyFirstTag" = "AAA"
		"MySecondTag" = "BBB"
	}

Add-DatabricksCluster -CustomTags $tags -NumWorkers 1 -ClusterName "Test API" -SparkVersion '5.0.x-ml-scala2.11' -NodeTypeId 'Standard_DS3_v2'  -AutoterminationMinutes 10
`

**Comment by koder101** [comment]
@gbrueckl : 
Hi, I am getting the same error for **-Libraries** parameter in **Add-DatabricksJob** command. The below sysntax is not working -

`$libraries = @{"jar" = "dbfs:/jars/sqldb.jar"}`

**Error:**

> Invoke-RestMethod : {"error_code":"MALFORMED_REQUEST","message":"Could not parse request object: Expected object for field libraries, found STRING"}

**Verbose output:**

```
"libraries":  [
                      "System.Collections.Hashtable"
                  ],
```

Could you please look into this.

**Comment by gbrueckl** [comment]
just uploaded a new version (9.2.0) which now supports this syntax:

```
$libraries = @{"jar" = "dbfs:/jars/sqldb.jar"}
Add-DatabricksJob -Name "MyTestJob" -ClusterID $cluster.cluster_id -Libraries $libraries -NotebookPath "/MyNotebook"
```

and thanks for the feedback!
