### ISSUE TITLE
Add-DatabricksCluster error when creating autoscale cluster

### ISSUE THREAD

**Issue by glloyd2010f** [gbrueckl/Databricks.API.PowerShell#60]
When attempting to leverage the below code, which is configured to be an autoscale cluster I am getting an error relating to line 182 of the ClusterAPI.ps1 `Add-DatabricksCluster` function. I have attached the cluster configuration json via a zip file to this issue as well.

```
$json = get-content 'C:\dev\pathToRepo\dbw.cluster.config.json'
$object = $json | convertfrom-json
$object
Add-DatabricksCluster -ClusterObject $object
```

Here is the error message that I receive.
```
InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\DatabricksPS\1.9.9.13\Public\ClustersAPI.ps1:182
Line |
 182 |            ($prop.Name -in @("num_workers")) -or #some properties need …
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\DatabricksPS\1.9.9.13\Public\ClustersAPI.ps1:182
Line |
 182 |            ($prop.Name -in @("num_workers")) -or #some properties need …
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
```

Something to note is that when running locally it will continue and actually create the cluster. However, when attempting to leverage the module in Azure DevOps it will fail the pipeline.

**Reproduction Steps with DatabricksPS Version 1.9.9.13**
1. Connect to Azure
    1. `Connect-AzAccount`
2. Import Module
    1. `Import-Module DatabricksPS -DisableNameChecking -Force`
3. Set Azure Databricks Workspace Resource ID
    1. `$databricksId = '/subscriptions/<subscriptionId>/resourceGroups/<rgName>/providers/Microsoft.Databricks/workspaces/<workspaceName't`
4. Set Databricks Environment leveraging Az Context
    1. `Set-DatabricksEnvironment -AzureResourceID $databricksId -UsingAzContext`
5. Import Cluster Config JSON and Convert it to a PS Object
    1. `$json = get-content 'C:\dev\pathToRepo\dbw.cluster.config.json`
    1. `$object = $json | convertfrom-json`
6. Run Cluster Creation Command
    1. `Add-DatabricksCluster -ClusterObject $object`

If I am doing something wrong here please let me know.

**Additional Notes**
I did go to the module file and I did a comment out of the lines between 179-188 that was causing the error, looks like below. This no longer caused the error to happen locally. However, this would likely break functionality in other parts.

```
    $nonEmptyParameters = @{}
    foreach ($prop in $parameters.GetEnumerator()) {
      # if (
      #     ($prop.Name -in @("num_workers")) -or #some properties need to allow empty/0 value
      #     ($prop.Value.GetType().Name -eq "Boolean") -or # for boolean values we also want to keep "False" as value
      #     ($prop.Value -and $($prop.Value | ConvertTo-Json -Compress) -notin @("{}", "[]")) # value is not empty 
      # ) {
        $nonEmptyParameters.Add($prop.Name, $prop.Value)
      # }
    }
```

[dbw.cluster.config.json.zip](https://github.com/gbrueckl/Databricks.API.PowerShell/files/9839676/dbw.cluster.config.json.zip)

**Comment by gbrueckl** [comment]
just published v1.9.9.16 which should fix the issue - at least I could deploy your cluster from the JSON file

**Comment by glloyd2010f** [comment]
Ooo I will get that downloaded, test, and let you know how it goes locally and from Azure DevOps.

**Comment by glloyd2010f** [comment]
I can confirm that `v1.9.9.16` was successful locally and in Azure DevOps and did throw the error I mentioned. Thank you for noticing that issue and getting it fixed so quickly!!!
