### ISSUE TITLE
Error on Set-DatabricksPermissions 

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#61]
Hello,  

Would you kindly fix this issue.  This used to work in prior versions but it is not working now in version 1.9.9.14.  
Here is how you can reproduce it:

$acl = @(
        @{
            group_name       = "users"
            permission_level = "CAN_USE"        
        }
    )

Set-DatabricksPermissions -ObjectType "TOKENS" -AccessControlList $acl -Verbose

Invoke-RestMethod: /Users/saldroubi/.local/share/powershell/Modules/DatabricksPS/1.9.9.14/Public/General.ps1:96:13
Line |
  96 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error_code":"RESOURCE_DOES_NOT_EXIST","message":"tokens tokens does not exist"}

**Comment by saldroubi** [comment]
I think I know why this is happening now.  They have changed the API>  It seems that you must have at least one token created before you can set the permission.  This does not make any sense. 
I don't like the workaround of create a temporary token so I can set the permissions.  What is your opinion?

**Comment by gbrueckl** [comment]
your code is actually working fine for me - probably because I already had some tokens created in my environment.
Where did you read that at least one token must have been created before? could not find it in the docs

also, could you please post the full output of your `-Verbose` execution of the command, thanks

**Comment by saldroubi** [comment]
You have to create a new workspace without  creating any tokens to reproduce.  I was using Azure context to set the environment like as so:
  Set-DatabricksEnvironment -UsingAzContext -AzureResourceID $resourceID -Verbose

and then calling setting permissions as shown above which generated the error. If you go to the UI you will see the message when you hover over the Permission Settings that says **"Token permissions can be set only if at least one token has been created in the workspace."**  If you create a token you can't reproduce this again.  See attached image.

What do you think should be done here?
 
![token_issue](https://user-images.githubusercontent.com/16247245/198379695-56eb4625-5a23-4a95-b369-0cc6d8632f90.jpg)

**Comment by gbrueckl** [comment]
ok, thanks for the info - I can reproduce it now also on my side

unfortunately I do not think there is an easy workaround except creating a temporary token first as you already suggested. I also tried using the PUT API call instead the PATCH (which is used by default and if you do not specify `-Overwrite`) but the results are the same

but all API calls fail, even the simplest GET request unless a token has already been created upfront

**Comment by gbrueckl** [comment]
I would suggest to raise a bug at Databricks as this has to be fixed on their side

**Comment by saldroubi** [comment]
I guess this is not an issue you can control on your end.  Thank you for the looking into it.
