### ISSUE TITLE
Update-DatabricksClusterPolicy error

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#62]
Azure Databricks has added special cluster policies.  One of the is called "Job Compute"  I am not able to update the definition for that cluster policy due to attributes they added to this policy.  Would you kindly fix this?

Thank you for this wonderful module. 

Here is example code:

$policyName = 'Job Compute'

$policy = Get-DatabricksClusterPolicy | Where-Object { $_.name -eq $PolicyName } 

$policyId = $policy.policy_id
$policyName = $policy.name

$policy | Update-DatabricksClusterPolicy -PolicyID $policyId -PolicyName $policyName 

nvoke-RestMethod: /Users/saldroubi/.local/share/powershell/Modules/DatabricksPS/1.9.9.14/Public/General.ps1:96:13
Line |
  96 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error_code":"INVALID_PARAMETER_VALUE","message":"Changing policy_family_id is forbidden for default cluster policies. Clone this policy to change the policy family."}

**Comment by gbrueckl** [comment]
well, the error message comes directly from the Databricks API indicating you try to do something that is not supported - this is not related to this PowerShell module

**Comment by gbrueckl** [comment]
closed as not related to the module
