### ISSUE TITLE
Error Updating Instance Pools - missing instance_pool_id in body

### ISSUE THREAD

**Issue by jdocampo** [gbrueckl/Databricks.API.PowerShell#64]
InstancePoolId parameter is mandatory but is not used in the API call, giving an error.
There should be an additional line:

`$parameters | Add-Property -Name "instance_pool_id" -Value $InstancePoolId -Force`

right before adding the instance_pool_name parameter to the dict.

**Comment by jdocampo** [comment]
Created PR https://github.com/gbrueckl/Databricks.API.PowerShell/pull/65

**Comment by gbrueckl** [comment]
this will be published with `v1.9.9.18` later today
