### ISSUE TITLE
Add-DatabricksSCIMUser -UserName me@mydomain.com  -Entitlements @("workspace-access","databricks-sql-access")

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#66]
The entitlements workspace-access and databricks-sql-access are valid according to the documentation https://docs.databricks.com/administration-guide/users-groups/users.html#assign-entitlements-to-a-workspace-user
In facts they are not getting set by default as Databricks is calming when I add a new user.   So I want to explicitly set these entitlements.  Would you please fix this please?

Add-DatabricksSCIMUser -UserName me@mydomain.com -GroupNames "users" -Entitlements @("workspace-access","databricks-sql-access")
Add-DatabricksSCIMUser: /Users/saldroubi/Dropbox/git/dbr-mantain/ssa_scratch_workspace_changes.ps1:21:84
Line |
  21 |  … s "users" -Entitlements @("workspace-access","databricks-sql-access")
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Entitlements'. The argument "workspace-access" does not belong to the set
     | "allow-instance-pool-create,allow-cluster-create" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command
     | again.

Also, how do I get a list of permissions/entitlements of  users.   When I use Get-DatabricksSCIMUser I am not getting those two permissions listed above for my users even though they have them. 

Thank you.

**Comment by gbrueckl** [comment]
the new entitlements were added in v1.10.0.0 which was just published

regarding the issue of retrieving the entitlements for users - it seems only explicitly granted entitlements are returnd
so, e.g. if the user is an admin, it will not return all entitlements as they are implcitly granted to an admin-user anyway
you can however also explicitly grant the entitlements and then they are also returned 
(at least according to my quick tests)

**Comment by gbrueckl** [comment]
I just pass through the entitlements to the API so I would assume a bug with the API - you can also check using `-Verbose`

dont think there is much I can do about this :(

**Comment by gbrueckl** [comment]
maybe its not  premium workspace and you cannot control finer grained access?
just an idea ...

**Comment by saldroubi** [comment]
Somehow I worked around this issue so closing.
