### ISSUE TITLE
How to do paging with Jobs 2.1 api?

### ISSUE THREAD

**Issue by successhawk** [gbrueckl/Databricks.API.PowerShell#67]
Hi, 
Can you please provide an example of how to use Get-DatabricksJob (api/2.1/jobs/list) to get all jobs, or more than the default limit 20 jobs?  It appears to me that it only retrieves the first "page", and there is no way for me to request the next page or request all of the data. 
Also, I think you might have an issue with your validation logic on JobId parameter for Update-DatabricksJob that is related to this when JobsAPIVersion is set to 2.1, because it doesn't retrieve all of the job ids.  Sorry, I don't have time to reproduce.

Currently, to work around this.  I am setting the environment to 2.0 for list operations and 2.1 for other operations.  Thanks

**Comment by gbrueckl** [comment]
just added the missing parameters to the cmdlet in `v1.11.0.1`

doing the pagination is still up to you though

**Comment by successhawk** [comment]
Thanks. I haven't tried it, but that looks good to me.  Did you look into [validation logic on JobId parameter for Update-DatabricksJob](DatabricksJobhttps://github.com/gbrueckl/Databricks.API.PowerShell/blob/3c66d524fffaff576efd8e5b9a55d2028847d41a/Modules/DatabricksPS/Public/JobsAPI.ps1#L400)?  When the environment is set to 2.1, I believe it only grabs the first page of Ids and therefore throws an inaccurate validation error in most cases.

**Comment by gbrueckl** [comment]
oh, thats true! will have a look!

**Comment by gbrueckl** [comment]
the validation is only used when you are using PowerShell ISE  (which I do not think a lot of people do anymore)

so i also removed the validation if Jobs API version 2.1 is used
