### ISSUE TITLE
Update-DatabricksSCIMGroup  -Entitlements @("workspace-access", "databricks-sql-access") parameter missing

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#68]
Hello, 

Groups like "users" can have entitlement like "workspace-access" and "databricks-sql-access". 
I would like to update the entitlements to the users group but I am not finding a way to do it with 
Update-DatabricksSCIMGroup 

I have noticed that Add-DatabricksSCIMGroup has an entitlement parameter but not the update. 
Please see attached file from UI. 

Could you please add this feature?

![group_scim_Issue](https://user-images.githubusercontent.com/16247245/213576650-54ff6b45-ad5f-41f9-ac03-a056a0f039f6.jpg)

**Comment by gbrueckl** [comment]
this will be fixed in the next release

**Comment by gbrueckl** [comment]
just published `v1.11.0` which should fix this

**Comment by saldroubi** [comment]
Thank you this is working now with the new version.

**Comment by saldroubi** [comment]
Thank you this is working now with the new version.
