### ISSUE TITLE
Error when trying to set the acl on sqlwarehouse end point using Set-DatabricksPermissions 

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#69]
I am not sure if I am passing all the parameters needed.  I am a little confused about this function.  Here is the code:

$acl = @(
          @{
            group_name        = "users"
            permission_level = "CAN_RESTART"        
          }
        )
$sqlEndPointId = Get-DatabricksSqlEndpoint | Where-Object { $_.name -eq "sql" } | Select-Object -ExpandProperty id

Get-DatabricksPermissions -SQLEndpointID $sqlEndPointId
Set-DatabricksPermissions -SQLEndpointID $sqlEndPointId -AccessControlList $acl

**Error below:**

Set-DatabricksPermissions: /Users/saldroubi/Dropbox/git/dbr-mantain/ssa_scratch_workspace_changes.ps1:24:1
Line |
  24 |  Set-DatabricksPermissions -SQLEndpointID $sqlEndPointId -AccessContro …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Parameter -ObjectID is mandatory for this API call!

Invoke-RestMethod: /Users/saldroubi/.local/share/powershell/Modules/DatabricksPS/1.10.0.0/Public/General.ps1:96:13
Line |
  96 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error_code":"INTERNAL_ERROR","message":"Unhandled Permission level"}

**Comment by gbrueckl** [comment]
first part will be fixed in next releaes

the second issue is related to your ACL - "CAN_RESTART" is not a permission available for SQL Warehouses
use this to get the available permissions that you can use for ACLS for SQL warehouses
`Get-DatabricksPermissionLevels -SQLEndpointID $sqlEndPointId `

**Comment by gbrueckl** [comment]
just published `v1.11.0` which should fix this

**Comment by saldroubi** [comment]
Seems to be working now. Thank you for fixing.
