### ISSUE TITLE
Error on: Set-DatabricksPermissions -ObjectType "TOKENS" -AccessControlList $acl -Verbose

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#71]
The code below used to work but now with latest release I am getting an error.  Would you please fix?

 $acl = @(
        @{
            group_name       = "users"
            permission_level = "CAN_USE"        
        }
    )
    
    Set-DatabricksPermissions -ObjectType "TOKENS" -AccessControlList $acl -Verbose

**Error below:** 
Set-DatabricksPermissions: /Users/saldroubi/Dropbox/git/dbr-mantain/ssa_VCMaintain.ps1:74:5
Line |
  74 |      Set-DatabricksPermissions -ObjectType "TOKENS" -AccessControlList …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'authorization/$($ObjectType.ToLower())' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path
     | was included, verify that the path is correct and try again.

**Comment by gbrueckl** [comment]
there was quite some rework recently - guess this broke some old code
should be fixed again with `v1.11.0.4`
