### ISSUE TITLE
SQL statement support?

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#72]
I noticed this sql cli module https://docs.databricks.com/dev-tools/databricks-sql-cli.html#databricks-sql-cli
I was wondering if can do the same functionality with your PowerShell module.  It doesn't seem to be there or am I missing something?

Sincerely,

**Comment by gbrueckl** [comment]
what you can do as of now is the following:
```
$sqlContext = Get-DatabricksExecutionContext -ClusterID $SQLClusterID -Language "sql"
$cmdGetDatabases = $sqlContext | Start-DatabricksCommand -Command "SHOW DATABASES"
$databases = ($cmdGetDatabases | Get-DatabricksCommandResult -AwaitCompletion).databaseName
```

which will run the `SHOW DATABASES` (or any other SQL) command/query against your cluster.

Please note, this uses a regular cluster and not SQL Warehouse!

**Comment by saldroubi** [comment]
This will not work for me since I need to run sql against the sql warehouse endpoint. 
Thank you.
