### ISSUE TITLE
Calling module functions from Web server question

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#74]
This is a question and not an issue. I am wondering if it is possible to wrap/call these functions from a web server. 

For example, using php:
<?php
$command = "powershell.exe -File path/to/your/script.ps1";
$output = shell_exec($command);
echo $output;
?>
and show the results to the user.  Someone wrote an article about this in general here:  http://vcloud-lab.com/entries/powershell/executing-powershell-script-from-php-html-web-server

The idea is to create a web app for managing many workspaces.  The user can pick one or N workspaces and perform certain functions based on a web menu.  I built this using Out-ConsoleGridView  https://devblogs.microsoft.com/powershell/introducing-consoleguitools-preview/. But thinking of making this a web app calling your module functions in the backend.

Thank you.

**Comment by gbrueckl** [comment]
I guess for this usecase you should rather use the Databricks REST API directly or use an existing wrapper for the language you also write the web app in, e.g. Python

Please also note, that the Databricks REST APIs currently do not support CORS which makes such scenarios quite hard

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: saldroubi ***@***.***>
Sent: Sunday, February 5, 2023 3:07:32 AM
To: gbrueckl/Databricks.API.PowerShell ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gbrueckl/Databricks.API.PowerShell] Calling module functions from Web server question (Issue #74)


This is a question and not an issue. I am wondering if it is possible to wrap/call these functions from a web server.

For example, using php:

and show the results to the user. Someone wrote an article about this in general here: http://vcloud-lab.com/entries/powershell/executing-powershell-script-from-php-html-web-server

The idea is to create a web app for managing many workspaces. The user can pick one or N workspaces and perform certain functions based on a web menu. I built this using Out-ConsoleGridView https://devblogs.microsoft.com/powershell/introducing-consoleguitools-preview/. But thinking of making this a web app calling your module functions in the backend.

Thank you.

**Comment by saldroubi** [comment]
Ok, but there are some PowerShell webservers, right?

**Comment by gbrueckl** [comment]
to be honest I do not know and I think it would be the fundamentally wrong technology to build webservers
If you still want to try, thats up to you, but there will be no efforts done for this module to support PowerShell webservers
