### ISSUE TITLE
EnableElasticDisk should be true by default when deploying a new cluster on Azure

### ISSUE THREAD

**Issue by alessio-cuzzocrea** [gbrueckl/Databricks.API.PowerShell#75]
Hi,
as the title states, this option should be true when using Azure, since this is the only option, or at least raise a warning.

The problem is that the Databricks API on azure accepts the `enable_elastic_disk=false` even though you don't have any other option on Azure.

Thanks,
Alessio

**Comment by gbrueckl** [comment]
I dont quite understand - you can set `enable_elastic_disk` explicitly to false. If you do not provide a value, it will use the default from Databricks

I dont want to introduce any logic in the cmdlets as they should just be a wrapper for the underlying REST API and should behave the very same way

**Comment by alessio-cuzzocrea** [comment]
I understand your point of view, defaulting to `true` does not fit with an API wrapper. 

But I'll try to explain myself better, just for a heads-up: 
Issuing the command`Add-DatabricksCluster -ClusterObject $clusterObject` with Azure Databricks sets the `enable_elastic_disk` to `false` but we need to keep in mind that in Azure Databricks this option is always `true` as you can't setup local storage yourself in the UI and in the [docs it states that is automatically enabled](https://learn.microsoft.com/en-us/azure/databricks/clusters/configure#autoscaling-local-storage-azure). 

So in my opinion a warning could be nice to a user who deploys on DV1.

**Comment by gbrueckl** [comment]
just because it is "automatically enabled" does not mean you cannot disable it - thats what the parameter is for.
attaching a new disk to a worker takes some time and if you know in advance you will not need more diskspace you can disable elastic disks.
We had cases where wanted to explicitly disable it and the total runtime of our jobs halfed.

**Comment by alessio-cuzzocrea** [comment]
Thanks for you explanations.
