### ISSUE TITLE
Unity Catalog cluster creating

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#76]
We just enable Unity Catalog on one of our workspaces in Azure.  When I create a cluster using the UI, it is "Unity Catalog" enabled as shown in image by default. https://docs.databricks.com/data-governance/unity-catalog/compute.html
![unity_catalog_cluster](https://user-images.githubusercontent.com/16247245/219816553-dd1118e3-9b7b-4335-8236-ceaaa51ca8a1.jpg)

But when I create it using Add-DatabricksCluster it is not.  How do I create a unity catalog enable cluster?

I used Get-Databrickscluster but there is nothing in the output that tells me it is a unity catalog cluster (the one I created using UI)

{
  "cluster_id": "0216-170940-ajdvwrdv",
  "creator_user_name": "XXX@myorg.org",
  "spark_context_id": 9048380189107508765,
  "cluster_name": "spark-uc-aldrous",
  "spark_version": "11.3.x-scala2.12",
  "spark_conf": {
    "spark.hadoop.fs.azure.account.oauth2.client.id.storlakeprod.dfs.core.windows.net": "e79819ff-cf12-4505-2343f1-sdfd50da23365c7",
    "spark.databricks.delta.preview.enabled": "true",
    "spark.sql.session.timeZone": "America/Chicago",
    "spark.hadoop.fs.azure.account.auth.type.storlakeprod.dfs.core.windows.net": "OAuth",
    "spark.hadoop.fs.azure.account.oauth2.client.endpoint.storlakeprod.dfs.core.windows.net": "https://login.microsoftonline.com/332223/oauth2/token",
    "spark.hadoop.fs.azure.account.oauth2.client.secret.storlakeprod.dfs.core.windows.net": "{{secrets/kvadminprod/kvs-sp-vera-workspace-aa}}",
    "spark.hadoop.fs.azure.account.oauth.provider.type.storlakeprod.dfs.core.windows.net": "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider"
  },
  "azure_attributes": {
    "first_on_demand": 1,
    "availability": "ON_DEMAND_AZURE",
    "spot_bid_max_price": -1.0
  },
  "node_type_id": "Standard_E8ds_v4",
  "driver_node_type_id": "Standard_E32ds_v4",
  "spark_env_vars": {
    "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
  },
  "autotermination_minutes": 30,
  "enable_elastic_disk": true,
  "disk_spec": {},
  "cluster_source": "UI",
  "enable_local_disk_encryption": false,
  "instance_source": {
    "node_type_id": "Standard_E8ds_v4"
  },
  "driver_instance_source": {
    "node_type_id": "Standard_E32ds_v4"
  },
  "data_security_mode": "USER_ISOLATION",
  "runtime_engine": "STANDARD",
  "effective_spark_version": "11.3.x-scala2.12",
  "state": "TERMINATED",
  "state_message": "Inactive cluster terminated (inactive for 30 minutes).",
  "start_time": 1676567380076,
  "terminated_time": 1676658992032,
  "last_state_loss_time": 1676655354871,
  "last_activity_time": 1676657176922,
  "last_restarted_time": 1676655355009,
  "autoscale": {
    "min_workers": 2,
    "max_workers": 8,
    "target_workers": 2
  },
  "default_tags": {
    "Vendor": "Databricks",
    "Creator": "sam.aldroubi@vumc.org",
    "ClusterName": "spark-uc-aldrous",
    "ClusterId": "0216-170940-ajdvwrdv",
    "application": "workspace",
    "cost-center": "1086923000",
    "environment": "aa",
    "product": "data-platform"
  },
  "termination_reason": {
    "code": "INACTIVITY",
    "type": "SUCCESS",
    "parameters": {
      "inactivity_duration_min": "30"
    }
  },
  "init_scripts_safe_mode": false
}

Thank you.

**Comment by gbrueckl** [comment]
I guess it can be derived from `data_security_mode` in combination with this table
https://docs.databricks.com/data-governance/unity-catalog/compute.html#what-is-cluster-access-mode

but not something thats exposed as a separate attribute and hence will not be added as a separate parameter to the cmdlets
