### ISSUE TITLE
Add-DatabricksCluster with json string pipeline

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#77]
Hello,

I have the following case to share with you:

$jsonConfig = @"
{
    "cluster_name": "my-cluster",
    "spark_version": "11.3.x-scala2.12",
    "node_type_id": "Standard_D3_v2",
    "spark_conf": {
      "spark.speculation": true
    },
    "num_workers": 25,
    "data_security_mode": "USER_ISOLATION",
    "autotermination_minutes": 30
    
  }
"@

$hashConfig = $jsonConfig | ConvertFrom-Json -AsHashtable -Depth 20
$hashConfig | Add-DatabricksCluster
$jsonConfig | Add-DatabricksCluster

The first call to Add-DatabricksCluster succeeds but the second one fails with an the following error:
Invoke-RestMethod: /Users/saldroubi/.local/share/powershell/Modules/DatabricksPS/1.11.0.4/Public/General.ps1:96:13
Line |
  96 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error_code":"INVALID_PARAMETER_VALUE","message":"Exactly 1 of virtual_cluster_size, num_workers or autoscale must be specified."}

Just for my understanding, are we supposed to pass a json string or a hash table or a ps custom object?  I thought either way is acceptable but which way is best.  I am a little confused about this?  Is the json string converted to a hash table by the function.  How do you know it is a json string being passed?

Thank you.

**Comment by gbrueckl** [comment]
both, HashTable and PSCustomObject should work
passing in a JSON string will not work at the moment but I will add it in the next release

you can partially debug this on your own by adding `-Verbose` or `-Debug` to your calls and see what happens in the background
you can further have a look at the actual code here https://github.com/gbrueckl/Databricks.API.PowerShell/blob/master/Modules/DatabricksPS/Public/ClustersAPI.ps1#L114-L121

**Comment by gbrueckl** [comment]
just published v1.11.0.6 with the fix for JSON strings

**Comment by saldroubi** [comment]
This is working now.  
Thank you for fixing.
