### ISSUE TITLE
Get/Set-DatabricksPermissions for cluster policies

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#78]
I see no way to get or set the permissions on cluster policies.  Using the UI you can give users "CAN_USE" permission on a cluster policy.  I am trying to do that using your module but I couldn't find a way do it using Get/Set-DatabricksPermissions since the ObjectType is available. 
Here is the API URL:   https://docs.databricks.com/dev-tools/api/latest/permissions.html

I have tried something like this
Set-DatabricksPermissions -ObjectID 1637786306000 -ObjectType <NO Policy Object Type>
Am I doing something wrong or is it missing?

Thank you very much.

**Comment by gbrueckl** [comment]
just published a new version which now also supports Cluster Policies with the Permission-cmdlets
