### ISSUE TITLE
Cloud Shell compatibility...

### ISSUE THREAD

**Issue by robertwcyu** [gbrueckl/Databricks.API.PowerShell#8]
Azure Cloud Shell not working anymore.  I am not sure but I was using this in cloud shell and any command I request I get the result below on every command... Works fine in Windows Power Shell.  Looks like a auth. issue and wondering if there is a quick answer without me digging into the code.
 
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Language" content="en"/>
    <title>Databricks - Sign In</title>
    <meta name="viewport" content="width=960">
    <link rel="stylesheet" href="/login/bootstrap.min.css">
    <link rel="icon" type="image/png" href="login/favicon.ico" />

    <meta http-equiv="content-type" content="text/html; charset=UTF8">
<link rel="shortcut icon" href="favicon.ico"><link href="login/login.xxxxxx.css" rel="stylesheet"></head>
<body>
<div id="login-page"></div>
<script type="text/javascript" src="login/login.cb433fbe.js"></script></body>
</html>

**Comment by robertwcyu** [comment]
Please disregard issue... Windows Power Shell automatically logs you into Databricks work space if the token is expired.  My apologies...

**Comment by gbrueckl** [comment]
closing issue then
