### ISSUE TITLE
CommandNotFoundException

### ISSUE THREAD

**Issue by azurele** [gbrueckl/Databricks.API.PowerShell#9]
Hi, I have installed the Databricks latest Powershell Module and when I try to create a new cluster with the sample provided, I keep getting the below error.

$accessToken = "dapi123456789e672c4007052d4694a7c51"
$apiUrl = "https://westeurope.azuredatabricks.net"
Set-DatabricksEnvironment -AccessToken "$accessToken" -ApiRootUrl "$apiUrl"
```
Set-DatabricksEnvironment : The term 'Set-DatabricksEnvironment' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Can you please advise if there are any additional dependencies need to be loaded?

**Comment by gbrueckl** [comment]
it seems like something did not work correctly when you installed/imported the model
can you run 
`Get-Module -Name DatabricksPS`
if this does not work, please make sure that you run 
`Install-Module -Name DatabricksPS
Import-Module -Name DatabricksPS`
and then check the first command again

once the module is installed and imported correctly, you can list it commands which will also show the 
Set-DatabricksEnvironment commands
`Get-Command -Module DatabricksPS`

**Comment by azurele** [comment]
Yup, something got messed up with my download. I have got the latest again and imported, no more issues. Thanks for looking into it and the great work you have done!
